site_name: VSFGA

# repo_url: https://github.com/Diogo-Barboza/ProgrammingCodes

plugins: 
  - search

nav:
  - Home: index.md
  - 2024.2: 
    - Requisitos: sections/2024.2/Requisitos.md
    - EDA: sections/2024.2/EDA.md
    - FAC: sections/2024.2/FAC.md
  - 2025.1:
    - EDA - Jhon: sections/2025.1/EDA1/ementa.md
    - SDB2: sections/2025.1/SDB2/ementa.md
    - Testes de Software: sections/2025.1/Testes/ementa.md
    - IHC: sections/2025.1/IHC/ementa.md
    - Arquitetura e Desenho de Software: sections/2025.1/ADS/ementa.md
theme:
  name: material
  language: pt-BR
  logo: assets/logo3.png
  favicon: assets/favicon.png
  palette: 
    #Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Modo escuro

    #White mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Modo claro

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - content.code.copy
    - toc.integrate
    - content.tabs.link
    - header.autohide
  
  markdown_extensions:
    - markdown.extensions.attr_list
    - attr_list
